### ISSUE TITLE
B1-6

### ISSUE THREAD

**Issue by chrisjfoss** [Tyler-Thompson/Software-Engineering-Game-Application#24]
The unit tests related to the player sprite - which were implemented as a part of user story 6 to ensure that the player is being instantiated properly - do not clearly indicate their overarching purpose.  Instead of simply saying that a specific variable is what is should be, the related tests should be prefixed with something along the lines of: "Checking proper player instantiation:"

**Comment by Tyler-Thompson** [comment]
@Lmendien  is this resolved?
